#!/bin/sh

set -euxo pipefail

sudo apt install bootstrap-vz python-pip docker.io -y
sudo pip install pyrfc3339
git clone https://github.com/adensens/bootstrap-vz
git -C bootstrap-vz checkout 71ba58327cd0fe0864c8781a2816cb5a0d837d03
git clone manman
pushd manman

